// Code generated by Kitex v0.4.4. DO NOT EDIT.

package douyinservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	compoiste "tiktok/kitex_gen/compoiste"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	BasicFavoriteActionMethod(ctx context.Context, req *compoiste.BasicFavoriteActionRequest, callOptions ...callopt.Option) (r *compoiste.BasicFavoriteActionResponse, err error)
	BasicFavoriteListMethod(ctx context.Context, req *compoiste.BasicFavoriteListRequest, callOptions ...callopt.Option) (r *compoiste.BasicFavoriteListResponse, err error)
	BasicFeedMethod(ctx context.Context, req *compoiste.BasicFeedRequest, callOptions ...callopt.Option) (r *compoiste.BasicFeedResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kDouyinServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDouyinServiceClient struct {
	*kClient
}

func (p *kDouyinServiceClient) BasicFavoriteActionMethod(ctx context.Context, req *compoiste.BasicFavoriteActionRequest, callOptions ...callopt.Option) (r *compoiste.BasicFavoriteActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BasicFavoriteActionMethod(ctx, req)
}

func (p *kDouyinServiceClient) BasicFavoriteListMethod(ctx context.Context, req *compoiste.BasicFavoriteListRequest, callOptions ...callopt.Option) (r *compoiste.BasicFavoriteListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BasicFavoriteListMethod(ctx, req)
}

func (p *kDouyinServiceClient) BasicFeedMethod(ctx context.Context, req *compoiste.BasicFeedRequest, callOptions ...callopt.Option) (r *compoiste.BasicFeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BasicFeedMethod(ctx, req)
}
